//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.07 at 12:44:49 AM WET 
//


package pt.multicert.clientmanagement.ws_objects;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pt.multicert.clientmanagement.ws_objects package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pt.multicert.clientmanagement.ws_objects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListClientsResponse }
     * 
     */
    public ListClientsResponse createListClientsResponse() {
        return new ListClientsResponse();
    }

    /**
     * Create an instance of {@link ExecResult }
     * 
     */
    public ExecResult createExecResult() {
        return new ExecResult();
    }

    /**
     * Create an instance of {@link ClientInfo }
     * 
     */
    public ClientInfo createClientInfo() {
        return new ClientInfo();
    }

    /**
     * Create an instance of {@link GetClientByNIFResponse }
     * 
     */
    public GetClientByNIFResponse createGetClientByNIFResponse() {
        return new GetClientByNIFResponse();
    }

    /**
     * Create an instance of {@link AddClientResponse }
     * 
     */
    public AddClientResponse createAddClientResponse() {
        return new AddClientResponse();
    }

    /**
     * Create an instance of {@link GetClientByNameResponse }
     * 
     */
    public GetClientByNameResponse createGetClientByNameResponse() {
        return new GetClientByNameResponse();
    }

    /**
     * Create an instance of {@link ListClientsRequest }
     * 
     */
    public ListClientsRequest createListClientsRequest() {
        return new ListClientsRequest();
    }

    /**
     * Create an instance of {@link RemoveClientResponse }
     * 
     */
    public RemoveClientResponse createRemoveClientResponse() {
        return new RemoveClientResponse();
    }

    /**
     * Create an instance of {@link GetClientByNIFRequest }
     * 
     */
    public GetClientByNIFRequest createGetClientByNIFRequest() {
        return new GetClientByNIFRequest();
    }

    /**
     * Create an instance of {@link AddClientRequest }
     * 
     */
    public AddClientRequest createAddClientRequest() {
        return new AddClientRequest();
    }

    /**
     * Create an instance of {@link GetClientByNameRequest }
     * 
     */
    public GetClientByNameRequest createGetClientByNameRequest() {
        return new GetClientByNameRequest();
    }

    /**
     * Create an instance of {@link RemoveClientRequest }
     * 
     */
    public RemoveClientRequest createRemoveClientRequest() {
        return new RemoveClientRequest();
    }

}
