//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.06 at 06:43:58 PM WET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://multicert.pt/clientmanagement", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pt.multicert.clientmanagement.ws_objects;
